openapi: 3.0.0
info:
  title: Test API
  version: '1.0'
tags:
  - name: Test
    description: Test
paths:
  /test:
    get:
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                type: object
      tags:
        - Test
      description: Test
      operationId: test
      summary: Test
